### PR TITLE
Animations TODO completed.

### PR DESCRIPTION
**Pull request by durul**
Added Animation support.

### CODE REVIEW

**Comment by durul** [comment]
Hello , I have fixed tab and space problem and have added CoreSpotlight.

**Comment by JakeLin** [comment]
@durul thanks for killing all TODOs 👍👍👍, please let me know if you have any idea to improve the app. Let me know if you would like to be an internal contributor of the project.

**Comment by durul** [comment]
@JakeLin Thank you. Of Course I would like to be an internal contributor of the project.

**Comment by JakeLin** [comment]
@durul Invite sent. Let's have some fun together.

**Pull request merged**
