### PR TITLE
Add first UI tests

### PR DESCRIPTION
**Pull request by danielCarlosCE**
Test if city, icon and temperature are shown.

### CODE REVIEW

**Comment by JakeLin** [comment]
thanks @danielCarlosCE Good stuff 👍

**Comment by danielCarlosCE** [comment]
Oh great! 👊🏻

**Comment by JakeLin** [comment]
Please let me know if you want to make more improvements to the app, I can add you to the repo. Thanks 👍

**Comment by danielCarlosCE** [comment]
That would be great, @JakeLin ! I'm trying to find time to contribute more with the open source community.

**Comment by JakeLin** [comment]
@danielCarlosCE I have sent you an invite to be a maintainer of this project. Please let me know if you need anything, thanks.

**Pull request merged**
